### ISSUE TITLE
Missing Bracket in Relationships

### ISSUE THREAD

**Issue by SlamHammerfist** [DrOgres/tftflood#2]
The mod shows up in any system, not just Tales from the Loop, because of missing [ ] brackets in the module.json.
should be this instead:

"relationships": {
		"systems": [  <- add bracket
			{
			"id": "tftloop",
			"type": "system"
			}
		]   <- add bracket
	}

**Comment by DrOgres** [comment]
thanks for the report

fixed in 1.0.6
